version: '3.8'

services:
  api-service:
    build:
      context: .
      dockerfile: ./TimeCapsule.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db-service
    environment:
      - ConnectionStrings__DefaultConnection="Host=db-service;Port=5432;Database=TimeCapsuleDb;Username=postgres;Password=${DB_PASSWORD};"
      - Spotify__ClientId=${SPOTIFY_CLIENT_ID}
      - Spotify__ClientSecret=${SPOTIFY_CLIENT_SECRET}
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
  
  db-service:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: TimeCapsuleDb
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
  
volumes:
  pg-data:
  

    